### ISSUE TITLE
`list-all` not working on mac

### ISSUE THREAD

**Issue by execb5** [nverno/asdf-sml#1]
`asdf list-all sml` on mac is giving this output:

<img width="779" alt="matthias__tmuxinator_start_nutrabolt" src="https://user-images.githubusercontent.com/6979113/41824331-ee396248-77e4-11e8-8a1b-1b4cc2a36b2c.png">

Does anyone else have this issue? I think it should be just fixing the `grep` command in the list all.
There's some little differences between mac and linux shell commands.

**Comment by nverno** [comment]
I don't have a mac readily available to test it, but I could try to look into, or if you find something that works pull requests welcome
